# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ehci_pci"
        "ahci"
        "nvme"
        "usbhid"
        "sd_mod"
      ];
      kernelModules = [ "kvm-intel" ];
      extraModulePackages = [ ];
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c45a8d41-9b8d-4998-8365-d8810ce3b416";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/41EE-99E6";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/fasttank" = {
    device = "fasttank";
    fsType = "zfs";
  };

  fileSystems."/fasttank/test_dataset" = {
    device = "fasttank/test_dataset";
    fsType = "zfs";
  };

  fileSystems."/fasttank/containers" = {
    device = "fasttank/containers";
    fsType = "zfs";
  };

  fileSystems."/fasttank/containers/immich" = {
    device = "fasttank/containers/immich";
    fsType = "zfs";
  };

  fileSystems."/fasttank/containers/immich/immich_db" = {
    device = "fasttank/containers/immich/immich_db";
    fsType = "zfs";
  };

  fileSystems."/fasttank/containers/jellyfin" = {
    device = "fasttank/containers/jellyfin";
    fsType = "zfs";
  };

  fileSystems."/fasttank/containers/jellyfin/jellyfin_cache" = {
    device = "fasttank/containers/jellyfin/jellyfin_cache";
    fsType = "zfs";
  };

  fileSystems."/fasttank/containers/jellyfin/jellyfin_config" = {
    device = "fasttank/containers/jellyfin/jellyfin_config";
    fsType = "zfs";
  };

  fileSystems."/fasttank/containers/navidrome" = {
    device = "fasttank/containers/navidrome";
    fsType = "zfs";
  };

  fileSystems."/fasttank/containers/navidrome/navidrome_data" = {
    device = "fasttank/containers/navidrome/navidrome_data";
    fsType = "zfs";
  };

  fileSystems."/fasttank/containers/homepage" = {
    device = "fasttank/containers/homepage";
    fsType = "zfs";
  };

  fileSystems."/fasttank/containers/homepage/homepage_config" = {
    device = "fasttank/containers/homepage/homepage_config";
    fsType = "zfs";
  };

  fileSystems."/tank" = {
    device = "tank";
    fsType = "zfs";
  };

  fileSystems."/tank/appdata" = {
    device = "tank/appdata";
    fsType = "zfs";
  };

  fileSystems."/tank/appdata/immich" = {
    device = "tank/appdata/immich";
    fsType = "zfs";
  };

  fileSystems."/tank/appdata/immich/immich_data" = {
    device = "tank/appdata/immich/immich_data";
    fsType = "zfs";
  };

  fileSystems."/tank/backups" = {
    device = "tank/backups";
    fsType = "zfs";
  };

  fileSystems."/tank/users" = {
    device = "tank/users";
    fsType = "zfs";
  };

  fileSystems."/tank/videos" = {
    device = "tank/videos";
    fsType = "zfs";
  };

  fileSystems."/tank/music" = {
    device = "tank/music";
    fsType = "zfs";
  };

  fileSystems."/tank/projects" = {
    device = "tank/projects";
    fsType = "zfs";
  };

  fileSystems."/tank/books" = {
    device = "tank/books";
    fsType = "zfs";
  };

  fileSystems."/tank/dropbox" = {
    device = "tank/dropbox";
    fsType = "zfs";
  };

  fileSystems."/tank/games" = {
    device = "tank/games";
    fsType = "zfs";
  };

  fileSystems."/tank/documents" = {
    device = "tank/documents";
    fsType = "zfs";
  };

  fileSystems."/tank/photos" = {
    device = "tank/photos";
    fsType = "zfs";
  };

  fileSystems."/tank/backups/desktop" = {
    device = "tank/backups/desktop";
    fsType = "zfs";
  };

  fileSystems."/tank/downloads" = {
    device = "tank/downloads";
    fsType = "zfs";
  };

  fileSystems."/tank/backups/macbookpro" = {
    device = "tank/backups/macbookpro";
    fsType = "zfs";
  };

  fileSystems."/tank/backups/laptop" = {
    device = "tank/backups/laptop";
    fsType = "zfs";
  };

  fileSystems."/tank/users/jrh" = {
    device = "tank/users/jrh";
    fsType = "zfs";
  };

  fileSystems."/tank/photos/immich_backup_data" = {
    device = "tank/photos/immich_backup_data";
    fsType = "zfs";
  };

  fileSystems."/tank/photos/immich_backup_postgres_data" = {
    device = "tank/photos/immich_backup_postgres_data";
    fsType = "zfs";
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
